package handshake

const (
	HANDSHAKE_CERTIFICATE = iota + 1
	HANDSHAKE_CHANGECIPHERSPEC
	HANDSHAKE_CLIENTHELLO
	HANDSHAKE_CLIENTKEYEXCHANGE
	HANDSHAKE_SERVERHELLO
	HANDSHAKE_SERVERHELLODONE
	HANDSHAKE_SERVERKEYEXCHANGE
)
